### ISSUE TITLE
Not Pulling Latest Version

### ISSUE THREAD

**Issue by ainen** [hexlo/terraria-server-docker#1]
It seems that 1.4.3.2 is still being pulled even though 1436 is being reported by "get-latest-version.sh". This causes clients trying to connect to get the following error message: 

> You are not using the same version as this server.

**Comment by hexlo** [comment]
I can confirm the behaviour. I will investigate.

**Comment by hexlo** [comment]
It should be fixed. Could you confirm that it works on your end as well?

**Comment by ainen** [comment]
I can confirm that this resolved the issue. Version 1.4.3.6 is being pulled with this change.
