### ISSUE TITLE
[Feature Request] Server Version Selection

### ISSUE THREAD

**Issue by acorbett2012** [hexlo/terraria-server-docker#14]
With the introduction of the "undeluxe" version on the beta branch in steam it would be nice to be able to launch a server for that version
Version is 1.0.6.1 and does exist on the api

Either adding an env toggle from latest to undeluxe, or a specific version selection would work.

**Comment by hexlo** [comment]
I'll look into it in the next few days!

**Comment by hexlo** [comment]
After looking at the Undeluxe Edition, to my knowledge, it's not possible to easily add. Terraria did not support Linux until 1.3; the 1.0.6.1 server is only available for Windows. If I'm missing something, please let me know!

**Comment by acorbett2012** [comment]
It looks like you're right about linux server support. I wasn't aware of that, that's a bummer. I don't expect you to try and make that work, so you can close this if you want.
