### ISSUE TITLE
[Feature Request] ARM64 images

### ISSUE THREAD

**Issue by ChickenIQ** [hexlo/terraria-server-docker#5]
I would like you to add support for ARM64 processors, this can be done easily in the autobuild.
I see you are using Jenkins to autobuild. I am not familiar with it, but here's my github actions workflows file for reference.
https://github.com/ChickenIQ/portainer-templates/blob/main/.github/workflows/docker-image.yml

Edit: 
It's not as simple as building the docker image for arm64.
Building the image myself results in this error at runtime:
/init-TerrariaServer.sh: line 31: ./TerrariaServer.bin.x86_64: cannot execute binary file: Exec format error, the init script must be modified to use mono as suggested in the terraria wiki "mono --server --gc=sgen -O=all ./TerrariaServer.exe".

**Comment by jonnykking** [comment]
would love to see an arm64 build too!

**Comment by hexlo** [comment]
I'll look into it!

**Comment by hexlo** [comment]
I've made a working multi arch image supporting arm64. The issue now is not having access to an arm64 machine for the automated builds. So for now, I'll manually update that image. When I get an arm64 node for my builds, I will integrate the multi-arch support on the main image. 

Here is the image:

### **hexlo/terraria-server-multiarch:latest**

Let me know if you have any issues. 

Cheers.

**Comment by jonnykking** [comment]
OOOOOO!!!!!
testing now :)

**Comment by jonnykking** [comment]
Works a treat! Running on a free instance from https://cloud.oracle.com/

**Comment by ChickenIQ** [comment]
> I've made a working multi arch image supporting arm64. The issue now is not having access to an arm64 machine for the automated builds. So for now, I'll manually update that image. When I get an arm64 node for my builds, I will integrate the multi-arch support on the main image. 
> 
> Here is the image:
> 
> ### **hexlo/terraria-server-multiarch:latest**
> 
> Let me know if you have any issues. 
> 
> Cheers.

You don't need an arm64 node for building. You can just use qemu with docker buildx

**Comment by hexlo** [comment]
The thing with buildx is that you can't create a manifest to do a multi-arch image or target different stages for different architectures, as far as I know. I could support two different images that way, but my goal is to provide a single tag for both architectures, using a manifest. Haven't found a way to do that with the default Docker Buildkit.

**Comment by ChickenIQ** [comment]
I'm not exactly familiar with Jenkins, but if it doesn't support docker buildx, you could just use a script to do it.

I found an example which seems to be what you are aiming for, although the given script is a bit overcomplicated:
https://www.infracloud.io/blogs/multi-arch-containers-ci-cd-integration/

**Comment by hexlo** [comment]
I figured it out. Using Default Buildkit to target a stage in the Dockerfile for amd64 and then using buildx for the arm64, which skips the amd64 entrypoint in the Dockerfile. It feels like a hack, but it works :) Thanks for the read btw. So now the main image **_hexlo/terraria-server-docker_** will be updated every 2 hours for both architectures. Let me know if you have any issues.
